language: node_js
node_js:
  - "12"
cache: yarn
script:
  - yarn test
  - yarn build
  - cp CNAME build/CNAME
deploy:
  provider: pages:git
  edge: true
  local_dir: build
  target_branch: master
  skip_cleanup: true
  committer_from_gh: true
  token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: develop
