version: 2.1
orbs:
  node: circleci/node@7.1.0
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '20'
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - store_artifacts:
          path: build
workflows:
  test_my_app:
    jobs:
      - build
