version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.12'
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
workflows:
  test_my_app:
    jobs:
      - build
